[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --clean-alluredir

markers =
    smoke: Critical path smoke tests
    regression: Full regression suite
    login: Login page tests
    register: Register page tests
    catalog: Catalog page tests
    footer: Footer component tests
    navbar: NavBar component tests
    cart: Cart page tests
    wishlist: Wishlist page tests
    profile: Profile page tests